baseURL = "https://cicocinas.com/"
languageCode = "es-co"
paginate = 6
theme = "portio"
title = "CI Cocinas"

# Main Menu
[[menu.main]]
name = "Inicio"
url = "#home"
weight = 1
[[menu.main]]
name = "Nosotros"
url = "#about"
weight = 2
[[menu.main]]
name = "Servicios"
url = "#service"
weight = 3

# Sitemap Menu
[[menu.sitemap]]
name = "Contacto"
url = "contact/"
weight = 1

[params]
headerCTAName = "Contacto"
bannerCTAName = "Inicia tu proyecto"
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © 2021"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/xlearovo"
recaptchaSiteKey = "6LccaZAaAAAAAFEqeIP1PPadcgjJD9iDcy5vbWB9"
googleAnalytics = "G-5Q5X5LNSG2"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Carrera 64A # 4G-98, Bogotá, Colombia."
email = "info@cicocinas.com"
openingHours = "Lunes a Viernes de 7am - 5pm, Sabados de 8am - 12m"
phone = "+(57) 315 6000 996"

[params.map]
APIkey = "AIzaSyDyHSoyWRW5ROXqIPwzEMe2osAd7AIWzj4"
latitude = "4.627259"
longitude = "-74.119193"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/cicocinas/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/company/c-i-cocinas-s-a-s-/"
weight = 2
